
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: postgres-demo
    name: postgres-demo
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - image: 046222885654.dkr.ecr.eu-central-1.amazonaws.com/konveyor/postgres-demo:latest
                  imagePullPolicy: Always
                  name: postgres-demo
                  ports:
                    - containerPort: 8080
                  resources: {}
            restartPolicy: Always
            securityContext: {}
status: {}

...
