name: Konveyor app deploy to EKS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.27.0' # default is latest stable
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: nc-admin
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: 046222885654.dkr.ecr.eu-central-1.amazonaws.com
        REPOSITORY: konveyor
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:latest .
        docker push $REGISTRY/$REPOSITORY:latest

    - name: Update kube config
      run: aws eks update-kubeconfig --name konveyor
    
    - name: Deploy to EKS
      uses: swdotcom/update-and-apply-kubernetes-configs@v1
      with:
        k8-config-file-paths: |
          #postgres-secrets.yaml
          #postgres-storage.yaml
          postgres-deployment.yaml
          #postgres-secrets.yaml
          postgres-demo-deployment.yaml
          #postgres-demo-service.yaml
        replacement-method: defined
      env:
        IMAGE_TAG: ${{ github.sha }}
        
